apiVersion: v1
kind: Service
metadata:
  name: {{ template "robustName" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ if .Values.nodePortEnabled }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
