image:
  repository: debian
  tag: stable-slim

schedule: "*/1 * * * *"
command: |
  echo "I'm alive"
shell: "/bin/sh"

vars:
  MY_VAR: "value"

volumes:
  - name: data
    path: /data
    size: 10Gi
    storageClass: default

commonLabels:
  label1: value1
  label2: value2
