{{ if .Values.ingress }}{{ if .Values.ingress.nginxBasicAuth }}
{{- $robustName := include "robustName" .Release.Name -}}
{{- $resourceName := $robustName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $resourceName }}-basic-auth
  namespace: {{ .Release.Namespace }}
data:
  auth: {{ htpasswd .Values.ingress.nginxBasicAuth.user .Values.ingress.nginxBasicAuth.password  | b64enc }}
{{ end }}{{ end }}