{{- define "common.customFileConfigmap.tpl" -}}
{{- range .Values.volumes }}
  {{- if .fileName }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.robustName" .fileName }}
  namespace: {{ $.Release.Namespace }}
data:
  {{ .fileName }}: |
    {{- .fileContent | nindent 4 }}

  {{- end }}  
{{- end }}
{{- end -}}
