{{- range .Values.namespaces }}
{{- if and .podMaximumResources (and .podDefaultResources .podResourceOvercommit) }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .name }}
  namespace: {{ .name }}
spec:
  limits:
    - type: Container
      {{- if .podMaximumResources }}
      max:
        cpu: {{ .podMaximumResources.cpu }}
        memory: {{ .podMaximumResources.memory }}
      {{- end }}
      {{- if .podDefaultResources }}
      default:
        cpu: {{ .podDefaultResources.cpu }}
        memory: {{ .podDefaultResources.memory }}
      defaultRequest:
        cpu: {{ .podDefaultResources.cpu }}
        memory: {{ .podDefaultResources.memory }}
      {{- end }}
      maxLimitRequestRatio:
        {{- if .podResourceOvercommit }}
        cpu: {{ .podResourceOvercommit.cpu }}
        memory: {{ .podResourceOvercommit.memory }}
        {{ else }}
        cpu: 1
        memory: 1
        {{- end }}
{{- end }}
{{- end }}
