{{- range .Values.namespaces }}
{{- if and .quota .overcommit }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .name }}
spec:
  hard:
    limits.cpu: {{ .quota.cpu | mul .overcommit.cpu }}
    limits.memory: {{ .quota.memory | regexFind "[1-9]+" | mul .overcommit.memory }}{{ .quota.memory | regexFind "[a-zA-Z]+"  }}
    requests.cpu: {{ .quota.cpu }}
    requests.memory: {{ .quota.memory }}
    requests.storage: {{ .quota.storage }}
{{- end }}
{{- end -}}
