on:
  push:
    branches:
      - main
  pull_request:

name: Linting
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Kubeval
      uses: stefanprodan/kube-tools@v1.2.0
      with:
        kubectl: 1.16.2
        kustomize: 3.4.0
        helm: 2.16.1
        helmv3: 3.0.0
        command: |
          rm -rf manifests && true
          mkdir manifests
          helm template charts/namespaces --output-dir manifests
          find manifests/ -name '*.yaml' | xargs kubeval --ignore-missing-schemas -v 1.13.0
          find manifests/ -name '*.yaml' | xargs kubeval --ignore-missing-schemas -v 1.18.0
        