on:
  push:
    branches:
      - main
  pull_request:

name: Linting test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: yaml-lint
      run: make lint
