name: package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Extract tag version
      id: versioning
      run: |
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    # - name: Increase chart version
    #   id: increase_chart_version
    #   run: |


    - name: Extract chart version
      id: chart_version
      run: |
        CHART_VERSION=$(cat charts/onechart/Chart.yaml | grep version:)
        CHART_VERSION=${CHART_VERSION#version: }
        echo $CHART_VERSION
        echo ::set-output name=CHART_VERSION::$CHART_VERSION

    - name: Ensure tag and chart version matches
      run: |
        echo "Run ${{ steps.versioning.outputs.VERSION }}"
        echo "${{ steps.chart_version.outputs.CHART_VERSION }}"
        echo "$TAG_VERSION"
        echo "$CHART_VERSION"
        if [ "$TAG_VERSION" != "$CHART_VERSION" ]
        then
            echo "Tag version does not match chart version"
            exit 1
        fi
      env:
        TAG_VERSION: ${{ steps.versioning.outputs.VERSION }}
        CHART_VERSION: ${{ steps.chart_version.outputs.CHART_VERSION }}

    - name: Fetch tag
      id: fetch_tag
      run: |
        git tag
        VERSION_TAG=`git describe --tags`
        echo "::set-output name=version_tag::$VERSION_TAG"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Create commit and display commit message
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"
        git checkout main
        make package
        git add .
        git commit -am "Publishing ${{ steps.fetch_tag.outputs.version_tag }} to the helm repository"
        git push origin main
        echo "Publishing ${{ steps.fetch_tag.outputs.version_tag }} to the helm repository"
