name: package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    
    - name: Versioning
      id: versioning
      run: |
        echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

    - name: Fetch tag
      id: fetch_tag
      run: |
        git tag
        VERSION_TAG=`git describe --tags`
        echo "::set-output name=version_tag::$VERSION_TAG"
        echo "${{ steps.versioning.outputs.version }}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Display commit message
      run: echo "Publishing ${{ steps.fetch_tag.outputs.version_tag }} to the helm repository"
